diplom,part1,iter1
SvyatoslavLyskov/java-explore-with-me pull request #3
Opened 2023-08-26 11:22 UTC by SvyatoslavLyskov

2023-08-27 08:27 UTC, Frilock requested changes
Добрый день, 2 небольших просьбы и принимаем.

2023-08-27 08:27 UTC, Frilock commented on ewm-stats-service/stats-server/src/main/java/ru/practicum/repository/HitRepository.java
> +@Repository
Лишняя аннотация

2023-08-27 08:27 UTC, Frilock commented on ewm-stats-service/stats-server/src/main/resources/schema.sql
> +    app varchar(64) NOT NULL,
Данные размеры также лучше указывать в аннотации Column, чтобы не лазить лишний раз в скрипты, при сомнениях о размерности поля

2023-08-28 06:10 UTC, Frilock requested changes
Оставил комментарий

2023-08-28 06:10 UTC, Frilock commented on ewm-stats-service/stats-server/src/main/resources/schema.sql
> +    app varchar NOT NULL,
тут убирать не нужно, я просил чтобы те размерности которые указываете вы тут, вы также проставляли в column

2023-08-28 07:12 UTC, SvyatoslavLyskov commented on ewm-stats-service/stats-server/src/main/resources/schema.sql
> +    app varchar NOT NULL,
извиняюсь,случились разборки с бж и ее мужем,голова вообще в другую сторону работала,пришлось вчера залить его перцем,полгода мне угрожал расправой,очень рад,решил поделиться))))))

2023-08-28 08:14 UTC, Frilock approved these changes
Принято

2023-08-28 08:17 UTC, merged